import {ReactNode} from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import Provider from "./Provider";
import {routing} from '@/i18n/routing';
import {notFound} from 'next/navigation';
import 'swiper/css';
import 'swiper/css/pagination';
import "@/app/globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
    children: ReactNode;
    params: Promise<{locale: string}>;
};


export default async function RootLayout({children, params}: Props) {
    const {locale} = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }
  return (
      <html lang={locale} className="scroll-smooth" suppressHydrationWarning>
      <head>
          <meta name="viewport" content="width=device-width,initial-scale=1.0, user-scalable=no"/>
          <title></title>
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100..700;1,100..700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
              rel="stylesheet"/>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <NextIntlClientProvider>
          <Provider>
              {children}
          </Provider>
      </NextIntlClientProvider>
      </body>
      </html>
  );
}
